devtools::load_all()
collect_tables()
source("data-raw/1-teams.R")
source("data-raw/2-players.R")
# source("data-raw/3-guesses.R")
# source("data-raw/4-inventories.R")
# source("data-raw/5-sampled.R")
devtools::use_data(Teams, Players)
