unlink("data/", recursive = TRUE)
devtools::load_all()
collect_tables()
get_subj_info()
get_survey_responses()
source("data-raw/1-teams-and-players.R")
source("data-raw/2-guesses.R")
source("data-raw/3-performance.R")

source("data-raw/item-labels.R")
